collections:
  - name: community.general
    version: "*"
  - name: ansible.posix
    version: "*"
  - name: ansible.utils
    version: "*"
  - name: kubernetes.core
    version: "*"
  - name: kubevirt.core
    version: "*"
