---
- name: Cleanup host after Molecule
  hosts: all
  gather_facts: false
  become: true
  tasks:
    - name: Clean DNF caches
      ansible.builtin.command: dnf -y clean all
      changed_when: false
