---
dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/../default/requirements.yml

ansible:
  cfg:
    defaults:
      remote_tmp: /tmp/ansible
      callbacks_enabled: timer, profile_tasks, profile_roles
      deprecation_warnings: false
      forks: 50
      timeout: 90
      pipelining: true
      stdout_callback: default
    connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "true"
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=inventory/
  playbooks:
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    cleanup: ../default/cleanup.yml
    create: ../default/create.yml
    destroy: ../default/destroy.yml

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - prepare
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
