---
version: 3

images:
  base_image:
    name: registry.fedoraproject.org/fedora-bootc:41

dependencies:
  ansible_runner:
    package_pip: ansible-runner

  ansible_core:
    package_pip: ansible-core

  galaxy: ../requirements.yml

options:
  package_manager_path: /usr/bin/dnf5

additional_build_steps:
  prepend_base:
    - RUN $PKGMGR -y -q install python3-devel sudo util-linux
    - RUN groupadd --gid 1000 ansible
    - RUN useradd --uid 1000 --create-home --gid ansible --groups wheel ansible
    - RUN sed -i "/^%wheel/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers
