---
version: 3

images:
  base_image:
    name: registry.fedoraproject.org/fedora-minimal:42

dependencies:
  ansible_runner:
    package_pip: ansible-runner

  ansible_core:
    package_pip: ansible-core

  galaxy: ../requirements.yml

options:
  package_manager_path: /usr/bin/dnf5

additional_build_steps:
  prepend_base:
    - RUN $PKGMGR -y -q install python3-devel
