---
ansible:
  cfg:
    defaults:
      deprecation_warnings: false
  playbooks:
    create: ../default/create.yml
    destroy: ../default/destroy.yml
    converge: ../default/converge.yml
    verify: ../default/verify.yml
    cleanup: ../default/cleanup.yml
  env:
    ANSIBLE_FORCE_COLOR: true
  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --inventory=inventory/

dependency:
  name: galaxy
  options:
    requirements-file: ${MOLECULE_SCENARIO_DIRECTORY}/../default/requirements.yml

verifier:
  name: ansible

scenario:
  test_sequence:
    - dependency
    - destroy
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
