---
version: 3

images:
  base_image:
    name: docker.io/redhat/ubi10:latest

dependencies:
  ansible_runner:
    package_pip: ansible-runner

  ansible_core:
    package_pip: ansible-core

  galaxy: ../requirements.yml

options:
  package_manager_path: /usr/bin/dnf

additional_build_steps:
  prepend_base:
    - RUN $PKGMGR -y -q install python3-devel sudo
    - RUN groupadd -r ansible
    - RUN useradd -m -g ansible -G wheel ansible
    - RUN sed -i "/^%wheel/s/ALL\$/NOPASSWD:ALL/g" /etc/sudoers
