---
version: 3

images:
  base_image:
    name: docker.io/library/ubuntu:noble

dependencies:
  ansible_runner:
    package_pip: ansible-runner

  ansible_core:
    package_pip: ansible-core

  galaxy: ../requirements.yml

options:
  package_manager_path: /usr/bin/apt-get

additional_build_steps:
  prepend_base:
    - ENV DEBIAN_FRONTEND=noninteractive
    - RUN export DEBIAN_FRONTEND=noninteractive && \
      $PKGMGR -y update && \
      $PKGMGR -y -q install python3-dev && \
      $PKGMGR -y clean
