---
version: 3

images:
  base_image:
    name: docker.io/library/ubuntu:jammy

dependencies:
  ansible_runner:
    package_pip: ansible-runner

  ansible_core:
    package_pip: ansible-core

  galaxy: ../requirements.yml

options:
  package_manager_path: /usr/bin/apt-get

additional_build_files:
  - src: ensurepip.patch
    dest: ensurepip.patch

additional_build_steps:
  prepend_base:
    - ENV DEBIAN_FRONTEND=noninteractive
    - RUN export DEBIAN_FRONTEND=noninteractive && $PKGMGR -y update && $PKGMGR -y -q install python3 python3-dev python3-pip python3-venv && $PKGMGR -y clean
    - COPY _build/ensurepip.patch /ensurepip.patch
    - WORKDIR /usr/lib/python3.10/ensurepip
    - RUN patch </ensurepip.patch && rm /ensurepip.patch
