---
- name: admin-credentials | Ensure the admin group exists
  ansible.builtin.group:
    name: "{{ common_admin_group | default(common_admin_user) }}"
    gid: "{{ common_admin_gid | default(omit) }}"
    system: false
    state: present

- name: admin-credentials | Ensure the admin user exists
  ansible.builtin.user:
    name: "{{ common_admin_user }}"
    uid: "{{ common_admin_uid | default(omit) }}"
    group: "{{ common_admin_group | default(common_admin_user) }}"
    groups:
      - wheel
    append: true
    system: false
    shell: "{{ common_admin_shell }}"
    home: "{{ common_admin_home_dir }}"
    create_home: true
    state: present

- name: admin-credentials | Ensure SSH public key is authorized
  ansible.posix.authorized_key:
    user: "{{ common_admin_user }}"
    key: "{{ common_ssh_authorized_key }}"
    state: present
  no_log: true
  when: common_ssh_authorized_key is defined

- name: admin-credentials | Ensure current user password is set
  ansible.builtin.user:
    name: "{{ common_admin_user }}"
    password: "{{ common_admin_password }}"
  no_log: true
  when: common_admin_password is defined
