---
- name: Ensure extra CA certificates are present
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: "/usr/share/pki/ca-trust-source/anchors/{{ item | basename }}"
    owner: root
    group: root
    mode: "0644"
  loop: "{{ common_ca_certificates }}"

- name: Ensure system CA trust store is updated
  ansible.builtin.command: update-ca-trust
  changed_when: false
# vim: set ft=yaml.ansible:
