---
- name: Ensure sshd configuration is hardened
  ansible.builtin.template:
    src: ssh-hardening.conf.j2
    dest: /etc/ssh/sshd_config.d/00-ssh-hardening.conf
    owner: root
    group: root
    mode: "0640"
  when: common_ssh_hardening | bool

- name: Ensure sshd configuration hardening is disabled
  ansible.builtin.file:
    path: /etc/ssh/sshd_config.d/00-ssh-hardening.conf
    state: absent
  when: not common_ssh_hardening | bool
