---
- name: journald | Set the journal persistence
  when: common_journald_persistent is defined
  ansible.builtin.set_fact:
    journald_persistent: "{{ common_journald_persistent }}"

- name: journald | Set the journal max disk size
  when: common_journald_max_disk_size is defined
  ansible.builtin.set_fact:
    journald_max_disk_size: "{{ common_journald_max_disk_size }}"

- name: journald | Set the journal max file size
  when: common_journald_max_file_size is defined
  ansible.builtin.set_fact:
    journald_max_file_size: "{{ common_journald_max_file_size }}"

- name: journald | Set the journal user config
  when: common_journald_per_user is defined
  ansible.builtin.set_fact:
    journald_per_user: "{{ common_journald_per_user }}"

- name: journald | Set the journal compression mode
  when: common_journald_compression is defined
  ansible.builtin.set_fact:
    journald_compression: "{{ common_journald_compression }}"

- name: journald | Set the journal sync interval
  when: common_journald_sync_interval is defined
  ansible.builtin.set_fact:
    journald_sync_interval: "{{ common_journald_sync_interval }}"

- name: journald | Set the journal syslog forwarding config
  when: common_journald_forward_to_syslog is defined
  ansible.builtin.set_fact:
    journald_forward_to_syslog: "{{ common_journald_forward_to_syslog }}"

- name: journald | Set the journal rate limiting interval
  when: common_journald_rate_limit_interval_sec is defined
  ansible.builtin.set_fact:
    journald_rate_limit_interval_sec: "{{ common_journald_rate_limit_interval_sec }}"

- name: journald | Set the journal rate limiting burst amount
  when: common_journald_rate_limit_burst is defined
  ansible.builtin.set_fact:
    journald_rate_limit_burst: "{{ common_journald_rate_limit_burst }}"

- name: journald | Set the journal min disk size
  when: common_journald_keep_free is defined
  ansible.builtin.set_fact:
    journald_keep_free: "{{ common_journald_keep_free }}"

- name: journald | Set the journal max retention time
  when: common_journald_max_retention is defined
  ansible.builtin.set_fact:
    journald_max_retention: "{{ common_journald_max_retention }}"

- name: journald | Journald configuration
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.journald
