---
- name: Set the default postfix config
  ansible.builtin.set_fact:
    common_postfix_conf:
      relayhost: "{{ _smtp_server }}"
      inet_interfaces: "{{ common_mail_smtp_inet_interfaces }}"
      smtp_use_tls: "{{ (common_mail_smtp_tls in ('TLS', 'STARTTLS')) |
        ternary('yes', 'no') }}"
      smtp_tls_wrappermode: "{{ (common_mail_smtp_tls == 'TLS') |
        ternary('yes', 'no') }}"
      smtp_tls_security_level: "{{ (common_mail_smtp_user is defined) |
        ternary('encrypt', 'may') }}"

- name: Set configs for the mail user
  when: common_mail_smtp_user is defined
  ansible.builtin.set_fact:
    common_postfix_conf: "{{ common_postfix_conf | ansible.builtin.combine({
      'smtp_sasl_auth_enable': 'yes',
      'smtp_sasl_security_options': 'noanonymous, noplaintext',
      'smtp_sasl_tls_security_options': 'noanonymous',
      'smtp_sasl_password_maps': 'hash:/etc/postfix/sasl_passwd',
      }) }}"

- name: Configure the postfix files
  ansible.builtin.set_fact:
    common_postfix_files: []

- name: Configure the sasl password
  when: common_mail_smtp_user is defined
  ansible.builtin.set_fact:
    common_postfix_files: "{{ common_postfix_files | default([]) + [{
      'name': 'sasl_passwd'
      'content': _smtp_server ~ ' ' ~ common_mail_smtp_user ~ ':' ~ common_mail_smtp_password,
      'postmap': True | bool
      }]}}"

- name: Setup postfix
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.postfix
  vars:
    postfix_conf: "{{ common_postfix_conf }}"
    postfix_files: "{{ common_postfix_files }}"
    postfix_check: true
    postfix_backup: false
    postfix_backup_multiple: true
    postfix_manage_firewall: true
    postfix_manage_selinux: true

- name: Ensure root mails redirection is configured
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: "^#?root:"
    line: "root:           {{ common_mail_smtp_send_to }}"
  register: _postfix_aliases
  when: common_mail_smtp_send_to is defined
  notify:
    - restart postfix
    - postfix reload aliases

- name: Ensure Postfix service parent directory is present
  ansible.builtin.file:
    path: /etc/systemd/system/postfix.service.d
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: Ensure Postfix systemd service configuration is present
  ansible.builtin.copy:
    src: postfix_service.conf
    dest: /etc/systemd/system/postfix.service.d/postfix.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload postfix

- name: Flush handlers
  ansible.builtin.meta: flush_handlers

- name: Ensure Postfix "rpmnew" files are absent
  ansible.builtin.file:
    path: "{{ item }}.rpmnew"
    state: absent
  loop:
    - /etc/postfix/main.cf
    - /etc/aliases

- name: Ensure Postfix "rpmsave" files are absent
  ansible.builtin.file:
    path: "{{ item }}.rpmsave"
    state: absent
  loop:
    - /etc/postfix/main.cf
    - /etc/aliases
