---
- name: mail | Set the default postfix config
  ansible.builtin.set_fact:
    common_postfix_conf:
      relayhost: "{{ common_smtp_server }}"
      inet_interfaces: "{{ common_mail_smtp_inet_interfaces }}"
      smtp_use_tls: "{{ (common_mail_smtp_tls | default('') in ('TLS', 'STARTTLS')) | ternary('yes', 'no') }}"
      smtp_tls_wrappermode: "{{ (common_mail_smtp_tls | default('') == 'TLS') | ternary('yes', 'no') }}"
      smtp_tls_security_level: "{{ (common_mail_smtp_user is defined) | ternary('encrypt', 'may') }}"

- name: mail | Set configs for the mail user
  when: common_mail_smtp_user is defined
  ansible.builtin.set_fact:
    common_postfix_conf:
      "{{ common_postfix_conf | ansible.builtin.combine({'smtp_sasl_auth_enable': 'yes', 'smtp_sasl_security_options': 'noanonymous, noplaintext',
      'smtp_sasl_tls_security_options': 'noanonymous', 'smtp_sasl_password_maps': 'hash:/etc/postfix/sasl_passwd'}) }}"

- name: mail | Configure the postfix files
  ansible.builtin.set_fact:
    common_postfix_files: []

- name: mail | Configure the sasl password
  when: common_mail_smtp_user is defined
  ansible.builtin.set_fact:
    common_postfix_files:
      "{{ common_postfix_files | default([]) + [{'name': 'sasl_passwd', 'content': common_smtp_server ~ ' ' ~ common_mail_smtp_user ~ ':' ~ common_mail_smtp_password,
      'postmap': True | bool}]}}"

- name: mail | Setup postfix
  ansible.builtin.include_role:
    name: fedora.linux_system_roles.postfix
  vars:
    postfix_conf: "{{ common_postfix_conf }}"
    postfix_files: "{{ common_postfix_files }}"
    postfix_check: true
    postfix_backup: false
    postfix_backup_multiple: true
    postfix_manage_firewall: true
    postfix_manage_selinux: true

- name: mail | Ensure root mails redirection is configured
  ansible.builtin.lineinfile:
    path: /etc/aliases
    regexp: "^#?root:"
    line: "root:           {{ common_mail_smtp_send_to }}"
  register: common_postfix_aliases
  when: common_mail_smtp_send_to is defined
  notify:
    - restart postfix
    - postfix reload aliases

- name: mail | Ensure Postfix service parent directory is present
  ansible.builtin.file:
    path: /etc/systemd/system/postfix.service.d
    owner: root
    group: root
    mode: "0755"
    state: directory

- name: mail | Ensure Postfix systemd service configuration is present
  ansible.builtin.copy:
    src: postfix_service.conf
    dest: /etc/systemd/system/postfix.service.d/postfix.conf
    owner: root
    group: root
    mode: "0644"
  notify:
    - reload postfix

- name: mail | Flush handlers
  ansible.builtin.meta: flush_handlers

- name: mail | Ensure Postfix "rpmnew" files are absent
  ansible.builtin.file:
    path: "{{ item }}.rpmnew"
    state: absent
  loop:
    - /etc/postfix/main.cf
    - /etc/aliases

- name: mail | Ensure Postfix "rpmsave" files are absent
  ansible.builtin.file:
    path: "{{ item }}.rpmsave"
    state: absent
  loop:
    - /etc/postfix/main.cf
    - /etc/aliases
