---
- name: Set http proxy (if defined)
  ansible.builtin.lineinfile:
    path: "{{ base_proxy_config }}"
    regexp: '^http_proxy='
    line: 'http_proxy="{{ base_proxy_http_server }}"'
  when: base_proxy_http_server is defined and base_proxy_http_server|length > 0

- name: Set https proxy (if defined)
  ansible.builtin.lineinfile:
    path: "{{ base_proxy_config }}"
    regexp: '^https_proxy='
    line: 'https_proxy="{{ base_proxy_https_server }}"'
  when: base_proxy_https_server is defined and base_proxy_https_server|length > 0

- name: Set ftp proxy (if defined)
  ansible.builtin.lineinfile:
    path: "{{ base_proxy_config }}"
    regexp: '^ftp_proxy='
    line: 'ftp_proxy="{{ base_proxy_ftp_server }}"'
  when: base_proxy_ftp_server is defined and base_proxy_ftp_server|length > 0

- name: Set no_proxy list (if defined)
  ansible.builtin.lineinfile:
    path: "{{ base_proxy_config }}"
    regexp: '^no_proxy='
    line: 'no_proxy="{{ base_no_proxy }}"'
  when: base_no_proxy is defined and base_no_proxy|length > 0
