---
name: "Containers"

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

on:
  pull_request:
    branches:
      - main
    paths:
      - extensions/ee/**
  push:
    branches:
      - main
    paths:
      - extensions/ee/**
  workflow_dispatch:

jobs:
  build-and-push:
    name: Build all containers
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      attestations: write
      id-token: write
    env:
      REGISTRY: ghcr.io
      REGISTRY_IMAGE: ${{ github.actor }}/ansible-execution-env-${{ matrix.environment }}
    strategy:
      fail-fast: false
      matrix:
        environment:
          - fedora-41
          - fedora-42
          - rhel-10
          - rhel-9
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v5

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: "3.13"
          cache: pip

      - name: Install ansible-builder
        run: |
          pip install ansible-builder

      - name: Create the context
        working-directory: extensions/ee/${{ matrix.environment }}
        run: |
          ansible-builder create --file execution-environment.yml \
            --output-filename Dockerfile

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Get Docker Metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.REGISTRY_IMAGE }}
          tags: |
            type=raw,value=latest
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build Docker Container
        id: push
        uses: docker/build-push-action@v6
        with:
          context: ./extensions/ee/${{ matrix.environment }}/context
          platforms: linux/amd64,linux/arm64
          labels: ${{ steps.meta.outputs.labels }}
          annotations: ${{ steps.meta.outputs.annotations }}
          tags: ${{ steps.meta.outputs.tags }}
          push: true
          sbom: true
