---
name: Tag

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Upload releases
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Set up Python
        uses: actions/setup-python@v6
        with:
          python-version-file: ".python-version"

      - name: Set up UV
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: false
          cache-suffix: "release"

      - name: Install python dependencies
        run: |
          uv sync --locked --all-extras --dev
        shell: bash

      - name: Build the collection
        shell: bash
        run: |
          uv run ansible-galaxy collection build -v --force

      - name: Get the collection file
        id: collection
        shell: bash
        run: |
          TARBALL=$(ls -1 ./*.tar.gz)
          echo "tarball=$TARBALL" >>$GITHUB_OUTPUT

      - name: Generate the release notes
        shell: bash
        run: |
          uv run antsibull-changelog generate --only-latest \
            --output tmp-changelog.md --output-format md

      - name: Release to GitHub
        uses: softprops/action-gh-release@v2
        with:
          body_path: ./tmp-changelog.md
          draft: false
          prerelease: false
          files: ${{ steps.collection.outputs.tarball }}
          generate_release_notes: true
          append_body: true
          make_latest: true
# vim: set ft=yaml:
